// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Utilisation;

namespace Utilisation.Migrations
{
    [DbContext(typeof(ExoDataContext))]
    partial class ExoDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Utilisation.Entities.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActeurPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Realisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("FilmId");

                    b.ToTable("Film");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            ActeurPrincipal = "Mark Hammil",
                            Annee = 1977,
                            Genre = "Science-Fiction",
                            Realisateur = "Georges Lucas",
                            Titre = "Star Wars : Un nouvel espoir"
                        },
                        new
                        {
                            FilmId = 2,
                            ActeurPrincipal = "Mark Hammil",
                            Annee = 1980,
                            Genre = "Science-Fiction",
                            Realisateur = "Georges Lucas",
                            Titre = "Star Wars : L'empire contre-attaque"
                        },
                        new
                        {
                            FilmId = 3,
                            ActeurPrincipal = "Mark Hammil",
                            Annee = 1983,
                            Genre = "Science-Fiction",
                            Realisateur = "Georges Lucas",
                            Titre = "Star Wars : Le retour du Jedi"
                        },
                        new
                        {
                            FilmId = 4,
                            ActeurPrincipal = "Charlie Hunnam",
                            Annee = 2005,
                            Genre = "Société",
                            Realisateur = "Lexi Alexander",
                            Titre = "Hooligans"
                        },
                        new
                        {
                            FilmId = 5,
                            ActeurPrincipal = "Elijah Wood",
                            Annee = 2001,
                            Genre = "Heroic-Fantasy",
                            Realisateur = "Peter Jackson",
                            Titre = "LOTR - La communauté de l'anneau"
                        },
                        new
                        {
                            FilmId = 6,
                            ActeurPrincipal = "Elijah Wood",
                            Annee = 2002,
                            Genre = "Heroic-Fantasy",
                            Realisateur = "Peter Jackson",
                            Titre = "LOTR - Les deux tours"
                        },
                        new
                        {
                            FilmId = 7,
                            ActeurPrincipal = "Elijah Wood",
                            Annee = 2003,
                            Genre = "Heroic-Fantasy",
                            Realisateur = "Peter Jackson",
                            Titre = "LOTR - Le retour du roi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
